/*
 * DialogPrint.java
 *   Dialog para enviar reportes a imprimir
 * Parte de proyecto: SisCongresos
 * Author: Pedro Cardoso Rdz
 * Mail: cardp_2004@yahoo.com.mx
 * Place: Zacatecas Mexico
 * 
    Copyright © 2010 Pedro Cardoso Rodriguez

    SisCongresos is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or any 
    later version.

    SisCongresos is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with SisCongresos.  If not, see <http://www.gnu.org/licenses/>
 */

package Guis.Sistema;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Map;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.MediaPrintableArea;
import javax.print.attribute.standard.MediaSize;
import javax.print.attribute.standard.OrientationRequested;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.export.JRPrintServiceExporter;
import net.sf.jasperreports.engine.export.JRPrintServiceExporterParameter;

/**
 * @author  Pedro Cardoso Rodriguez
 */
public class DialogPrint extends javax.swing.JDialog {
    
    private PrintService[] impresoras;
    private JasperPrint impresor;
    private String error;
    private int tipoDoc;  //Tipo de documento donde: 1=lista de staff, 2=lista de eventos,
      //3=lista de ponentes, 4=Lista de asistentes
    private int resultado; // Resultado de la operacion donde -1=fallo, 0=cancelo, 1=ok
    
    /** Creates new form DialogPrint */
    public DialogPrint(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        Thread.setDefaultUncaughtExceptionHandler(new Logica.CatchUnhandledErrors((Ventana)parent));
        initComponents();
        btnClose.setColors(new Color(205,226,252),new Color(180,205,243),new Color(155,255,255));
        btnAceptar.setColors(new Color(205,226,252),new Color(180,205,243),new Color(155,255,255));        
        detectaImpresoras();
    }
    
    /** Detecta la lista de impresoras instaladas
     */
    private void detectaImpresoras(){
        impresoras = PrintServiceLookup.lookupPrintServices(null, null);
        if(impresoras.length==0)
            jcbImpresoras.addItem("<No se encontro impresora>");
        else
            for(int h=0;h<impresoras.length;h++)
                jcbImpresoras.addItem(""+impresoras[h].getName());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAll = new javax.swing.JPanel();
        pnlDtsPrsn = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jcbImpresoras = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblNumCopias = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPagIni = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPagFin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCopias = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnAceptar = new com.guis.SimpleButton();
        pnlNorth = new javax.swing.JPanel();
        btnClose = new com.guis.SimpleButton();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        pnlAll.setBackground(new java.awt.Color(223, 232, 254));
        pnlAll.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 3, true));
        pnlAll.setLayout(new java.awt.BorderLayout(5, 5));

        pnlDtsPrsn.setBackground(new java.awt.Color(223, 232, 254));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Titulo");

        jLabel1.setText("Seleccione impresora:");

        jPanel1.setBackground(new java.awt.Color(223, 232, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        lblNumCopias.setText("Num de paginas calculadas");

        jLabel3.setText("Imprimir desde:");

        jLabel4.setText("Hasta:");

        jLabel5.setText("Imprimir:");

        txtCopias.setText("1");

        jLabel6.setText("copias:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumCopias)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPagIni, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPagFin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCopias, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNumCopias)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPagIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtPagFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCopias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)))
        );

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDtsPrsnLayout = new javax.swing.GroupLayout(pnlDtsPrsn);
        pnlDtsPrsn.setLayout(pnlDtsPrsnLayout);
        pnlDtsPrsnLayout.setHorizontalGroup(
            pnlDtsPrsnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDtsPrsnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDtsPrsnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDtsPrsnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcbImpresoras, javax.swing.GroupLayout.Alignment.LEADING, 0, 281, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDtsPrsnLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlDtsPrsnLayout.setVerticalGroup(
            pnlDtsPrsnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDtsPrsnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbImpresoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnlAll.add(pnlDtsPrsn, java.awt.BorderLayout.CENTER);

        pnlNorth.setBackground(new java.awt.Color(223, 232, 254));

        btnClose.setText("X");
        btnClose.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        btnClose.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCloseKeyPressed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblTitle.setForeground(new java.awt.Color(0, 0, 153));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Impresion de reporte");

        javax.swing.GroupLayout pnlNorthLayout = new javax.swing.GroupLayout(pnlNorth);
        pnlNorth.setLayout(pnlNorthLayout);
        pnlNorthLayout.setHorizontalGroup(
            pnlNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNorthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlNorthLayout.setVerticalGroup(
            pnlNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblTitle))
        );

        pnlAll.add(pnlNorth, java.awt.BorderLayout.NORTH);

        getContentPane().add(pnlAll, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnCloseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCloseKeyPressed
        int key=evt.getKeyCode();
        if(key==java.awt.event.KeyEvent.VK_ESCAPE||key==java.awt.event.KeyEvent.VK_ENTER)
            dispose();
    }//GEN-LAST:event_btnCloseKeyPressed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        PrintRequestAttributeSet atribImp=new HashPrintRequestAttributeSet();
        JRPrintServiceExporter exporter = new JRPrintServiceExporter();
        OrientationRequested orientation;
        float base=8.5f;
        float alto=11f;
        int pagini, pagfin, copias;
        try{
            pagini=Integer.parseInt(txtPagIni.getText());
            pagfin=Integer.parseInt(txtPagFin.getText());
            copias=Integer.parseInt(txtCopias.getText());
            if(copias<1){
                resultado=-1; error="Numero de copias invalido";
                setVisible(false); return;
            }
            atribImp.add(MediaSize.findMedia(base,alto,MediaSize.INCH));
            orientation = OrientationRequested.PORTRAIT;
            atribImp.add(new MediaPrintableArea(0,0,base,alto,MediaSize.INCH));
            atribImp.add(orientation);
            exporter.setParameter(JRExporterParameter.JASPER_PRINT, impresor);
            exporter.setParameter(JRExporterParameter.START_PAGE_INDEX,pagini-1);
            exporter.setParameter(JRExporterParameter.END_PAGE_INDEX,pagfin-1);
            exporter.setParameter(JRPrintServiceExporterParameter.DISPLAY_PRINT_DIALOG, Boolean.FALSE);
            exporter.setParameter(JRPrintServiceExporterParameter.PRINT_SERVICE, impresoras[jcbImpresoras.getSelectedIndex()]);
            exporter.setParameter(JRPrintServiceExporterParameter.PRINT_REQUEST_ATTRIBUTE_SET,atribImp);
            for(int t=0;t<copias;t++) exporter.exportReport();
            setVisible(false);
        } catch(Exception exc){
            resultado=-1; error=exc.getMessage();
            setVisible(false); return;
        }
        resultado=1;
    }//GEN-LAST:event_btnAceptarActionPerformed

    /** Establece la impresion actual
     * @param tit Titulo del reporte a imprimir
     * @param tipoDoc Tipo de reporte a imprimir
     *   donde: 1=lista de staff, 2=lista de eventos, 3=Lista de ponentes, 4=Lista de asistentes
     * @param params parametros del documento a imprimir
     * @param lista Fuente de datos a imprimir (para los campos detail)
     * @return true si se pudo establecer los datos de impresion false en caso contrario
     */
    public boolean setImpresion(String tit,int tpDoc,Map<String,String> params,ArrayList lista){
        JRBeanCollectionDataSource campos;
        String[] formularios={"Staff","Eventos","Exps","Asis"};
        lblTitulo.setText(tit);
        tipoDoc=tpDoc;
        try{
            campos = new JRBeanCollectionDataSource(lista);
            if(lista!=null)
                impresor = JasperFillManager.fillReport(System.getProperty("user.dir")+"\\jasper\\"+formularios[tipoDoc-1]+".jasper",params,campos);
            else
                impresor = JasperFillManager.fillReport(System.getProperty("user.dir")+"\\jasper\\"+formularios[tipoDoc-1]+".jasper",params,new JREmptyDataSource());
            lblNumCopias.setText("Total paginas del reporte: "+((ArrayList)impresor.getPages()).size());
            txtPagIni.setText("1"); txtCopias.setText("1");
            txtPagFin.setText(""+((ArrayList)impresor.getPages()).size());
            resultado=0;
            return true;
        }
        catch(Exception exc){
            error=exc.getMessage();
            return false;
        }
    }
     
    /** Obtiene la descripcion del ultimo error
     * @return la descripcion del ultimo error
     */
    public String getError(){ return error; }
      
    /** Obtiene el codigo del resultado de la ultima operacion donde segun el valor significa:
     *   -1=fallo, 0=cancelo, 1=ok
     * @return
     */
    public int getResultado(){ return resultado;}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.guis.SimpleButton btnAceptar;
    private com.guis.SimpleButton btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jcbImpresoras;
    private javax.swing.JLabel lblNumCopias;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlAll;
    private javax.swing.JPanel pnlDtsPrsn;
    private javax.swing.JPanel pnlNorth;
    private javax.swing.JTextField txtCopias;
    private javax.swing.JTextField txtPagFin;
    private javax.swing.JTextField txtPagIni;
    // End of variables declaration//GEN-END:variables
    
}
