/*
 * DialogMessages.java
 *   Dialogo para mostrar mensajes al usuario
 * Parte de proyecto: SisCongresos
 * Author: Pedro Cardoso Rdz
 * Mail: cardp_2004@yahoo.com.mx
 * Place: Zacatecas Mexico
 * 
    Copyright © 2010 Pedro Cardoso Rodriguez

    SisCongresos is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or any 
    later version.

    SisCongresos is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with SisCongresos.  If not, see <http://www.gnu.org/licenses/>
 */

package Guis.Sistema;

import java.awt.Color;

/**
 * @author  Pedro Cardoso Rodriguez
 */
public class DialogMessages extends javax.swing.JDialog {
    
    public static final int ERROR_MESS=1;
    public static final int INF_MESS=2;
    public static final int QUES_MESS=3;
        
    /** Creates new form DialogConex */
    public DialogMessages(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        Thread.setDefaultUncaughtExceptionHandler(new Logica.CatchUnhandledErrors((Ventana)parent));
        initComponents();
        validateTree();
        btnClose.setColors(new Color(205,226,252),new Color(180,205,243),new Color(155,255,255));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAll = new javax.swing.JPanel();
        pnlNorth = new javax.swing.JPanel();
        btnClose = new com.guis.SimpleButton();
        lblTitle = new javax.swing.JLabel();
        pnlContainer = new javax.swing.JPanel();
        lblMessage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        pnlAll.setBackground(new java.awt.Color(223, 232, 254));
        pnlAll.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 160, 112), 3, true));
        pnlAll.setLayout(new java.awt.BorderLayout(5, 5));

        pnlNorth.setBackground(new java.awt.Color(223, 232, 254));

        btnClose.setText("X");
        btnClose.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        btnClose.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCloseKeyPressed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblTitle.setForeground(new java.awt.Color(255, 0, 0));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("! ! !");

        javax.swing.GroupLayout pnlNorthLayout = new javax.swing.GroupLayout(pnlNorth);
        pnlNorth.setLayout(pnlNorthLayout);
        pnlNorthLayout.setHorizontalGroup(
            pnlNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNorthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlNorthLayout.setVerticalGroup(
            pnlNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblTitle))
        );

        pnlAll.add(pnlNorth, java.awt.BorderLayout.NORTH);

        pnlContainer.setBackground(new java.awt.Color(223, 232, 254));
        pnlContainer.setLayout(new java.awt.BorderLayout());

        lblMessage.setText("Message");
        pnlContainer.add(lblMessage, java.awt.BorderLayout.CENTER);

        jLabel2.setForeground(new java.awt.Color(223, 232, 254));
        jLabel2.setText("||");
        pnlContainer.add(jLabel2, java.awt.BorderLayout.WEST);

        jLabel1.setForeground(new java.awt.Color(223, 232, 254));
        jLabel1.setText("||");
        pnlContainer.add(jLabel1, java.awt.BorderLayout.EAST);

        jLabel3.setForeground(new java.awt.Color(223, 232, 254));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("_");
        pnlContainer.add(jLabel3, java.awt.BorderLayout.SOUTH);

        pnlAll.add(pnlContainer, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlAll, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnCloseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCloseKeyPressed
        int key=evt.getKeyCode();
        if(key==java.awt.event.KeyEvent.VK_ESCAPE||key==java.awt.event.KeyEvent.VK_ENTER)
            dispose();
    }//GEN-LAST:event_btnCloseKeyPressed

    /** Muestra un mensaje
     * @param mess El texto del mensaje
     * @param type El tipo de mensaje donde segun los valores de las constantes
     *   ERROR_MESS para error, INF_MESS para informacion, QUES_MESS para pregunta o peticion;
     */
    public void setMessage(String mess,int type){
        lblTitle.setText(type==1?"! ! !":(type==2?"- O -":"? ? ?"));
        if(type==1){
            pnlAll.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 160, 112), 3, true));
            lblTitle.setForeground(Color.RED);
        }
        else if(type==2){
            pnlAll.setBorder(new javax.swing.border.LineBorder(Color.BLUE, 3, true));
            lblTitle.setForeground(Color.BLUE);
        }
        else if(type==3){
            pnlAll.setBorder(new javax.swing.border.LineBorder(Color.GREEN, 3, true));
            lblTitle.setForeground(Color.GREEN);
        }
        lblMessage.setText(mess); validateTree(); pack();
        setLocationRelativeTo(null); setVisible(true);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.guis.SimpleButton btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlAll;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlNorth;
    // End of variables declaration//GEN-END:variables
    
}
